development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ijjbxgmxstiodp:3OF0qDwGDpPgALyN2ZVqKLzWHF@ec2-54-221-244-62.compute-1.amazonaws.com:5432/d64jpvaump511c
